name: Ansible Galaxy Publish Collection
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ansible-galaxy collection build
      - run: |
          COLLECTION_NAMESPACE=$(yq e '.namespace' galaxy.yml)
          COLLECTION_NAME=$(yq e '.name' galaxy.yml)
          COLLECTION_VERSION=$(yq e '.version' galaxy.yml)
          ansible-galaxy collection publish \
            --api-key ${{ secrets.GALAXY_API_KEY }} \
            ${COLLECTION_NAMESPACE}-${COLLECTION_NAME}-${COLLECTION_VERSION}.tar.gz
