name: Ansible Galaxy Publish Collection

on:
  - push

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ansible-galaxy collection build
      - run: ansible-galaxy collection publish shubhamtatvamasi-test_collection-1.0.1.tar.gz ${{ secrets.GALAXY_API_KEY }}
